# Generated by Django 5.2 on 2025-04-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined',
            field=models.DateField(blank=True, null=True, verbose_name='joined date'),
        ),
    ]
