# Generated by Django 5.2 on 2025-04-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joined',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='joined date'),
        ),
    ]
