# Generated by Django 5.2.1 on 2025-06-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('users', '0007_remove_customuser_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='institutions.doctor', verbose_name='Assigned Doctor'),
        ),
    ]
