# Generated by Django 5.2.3 on 2025-06-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='updated_at',
        ),
    ]
