# Generated by Django 5.2.4 on 2025-07-05 16:17

from django.db import migrations
from django.contrib.auth.hashers import make_password


def hash_existing_security_answers(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')

    for user in CustomUser.objects.all():
        # Hash security answers that are not already hashed
        if user.security_answer_1 and not user.security_answer_1.startswith('pbkdf2_sha256$'):
            user.security_answer_1 = make_password(user.security_answer_1)
        if user.security_answer_2 and not user.security_answer_2.startswith('pbkdf2_sha256$'):
            user.security_answer_2 = make_password(user.security_answer_2)
        if user.security_answer_3 and not user.security_answer_3.startswith('pbkdf2_sha256$'):
            user.security_answer_3 = make_password(user.security_answer_3)
        user.save()


def reverse_hash_security_answers(apps, schema_editor):
    # This is a one-way migration - we cannot reverse hashing
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_security_answer_1_and_more'),
    ]

    operations = [
        migrations.RunPython(hash_existing_security_answers,
                             reverse_hash_security_answers),
    ]
