# Generated by Django 5.2.4 on 2025-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_hash_existing_security_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='One-time token for password reset', max_length=255, null=True, verbose_name='Password Reset Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, help_text='When the password reset token was created', null=True, verbose_name='Password Reset Token Created'),
        ),
    ]
