import { StyleSheet } from 'react-native';
import { themeColors } from '../theme/GlobalTheme';
import { rem } from '../utils/Responsive';

export const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        padding: rem(1.25),
        backgroundColor: themeColors.secondary,
    },
    section: {
        marginBottom: rem(1.75),
        backgroundColor: themeColors.white,
        borderRadius: rem(1),
        padding: rem(1.25),
        shadowColor: themeColors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    label: {
        fontWeight: 'bold',
        marginTop: rem(0.625),
        color: themeColors.primary,
        fontSize: rem(1),
    },
    value: {
        marginBottom: rem(0.375),
        fontSize: rem(1.0625),
        color: themeColors.text,
    },
    sectionTitle: {
        fontSize: rem(1.25),
        fontWeight: '700',
        marginBottom: rem(0.75),
        color: themeColors.primary,
        letterSpacing: 0.2,
    },
    placeholder: {
        color: themeColors.themeGray,
        marginBottom: rem(0.5),
        fontStyle: 'italic',
    },
    error: {
        color: 'red',
        marginTop: rem(0.5),
        fontWeight: 'bold',
    },
    resultBox: {
        backgroundColor: themeColors.secondary,
        borderRadius: rem(0.75),
        padding: rem(1),
        marginTop: rem(0.625),
        borderWidth: 1,
        borderColor: 'transparent',
        shadowColor: themeColors.primary,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 3,
        elevation: 1,
    },
    resultLabel: {
        fontWeight: 'bold',
        marginTop: rem(0.375),
        color: themeColors.primary,
        fontSize: rem(0.9375),
    },
    resultValue: {
        fontWeight: 'normal',
        color: themeColors.text,
        fontSize: rem(0.9375),
    },
    speciesRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: rem(0.25),
        marginTop: rem(0.375),
    },
    infoButton: {
        paddingTop: rem(0.25),
        borderRadius: rem(0.5),
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewAllTestsButton: {
        flexDirection: 'row',
        gap: rem(0.5),
        justifyContent: 'center',
        width: '100%',
        padding: rem(0.875),
        borderRadius: rem(0.5),
        alignItems: 'center',
        marginTop: rem(0.75),
        backgroundColor: themeColors.primary,
        shadowColor: themeColors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 4,
        elevation: 2,
    },
    viewAllTestsButtonText: {
        color: themeColors.white,
        fontWeight: 'bold',
        fontSize: rem(1),
        letterSpacing: 0.5,
    },
    noTestsMessage: {
        color: themeColors.themeGray,
        marginTop: rem(0.5),
        fontStyle: 'italic',
        textAlign: 'center',
    },
    patientInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: rem(0.25),
        marginBottom: rem(0.5),
        backgroundColor: themeColors.secondary,
        borderRadius: rem(0.375),
        paddingHorizontal: rem(0.5),
        paddingVertical: rem(0.25),
    },
    patientInfoValue: {
        flex: 1,
        color: themeColors.text,
        fontSize: rem(1),
        fontWeight: '500',
    },
});
