--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: bugsenseadmin
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO bugsenseadmin;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: bugsenseadmin
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO bugsenseadmin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO bugsenseadmin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO bugsenseadmin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO bugsenseadmin;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO bugsenseadmin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO bugsenseadmin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO bugsenseadmin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO bugsenseadmin;

--
-- Name: institutions_doctor; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.institutions_doctor (
    customuser_ptr_id bigint NOT NULL,
    doctor_id character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    institution_id integer NOT NULL
);


ALTER TABLE public.institutions_doctor OWNER TO bugsenseadmin;

--
-- Name: institutions_institution; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.institutions_institution (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    address text NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    website character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.institutions_institution OWNER TO bugsenseadmin;

--
-- Name: institutions_institution_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.institutions_institution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.institutions_institution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO bugsenseadmin;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO bugsenseadmin;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.users_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined date,
    email character varying(254) NOT NULL,
    full_name character varying(255) NOT NULL,
    gender character varying(10) NOT NULL,
    dob date,
    phone_number character varying(20),
    street character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    postcode character varying(20) NOT NULL,
    country character varying(100) NOT NULL,
    assigned_doctor_id bigint,
    is_doctor boolean NOT NULL,
    security_answer_1 character varying(255) NOT NULL,
    security_answer_2 character varying(255) NOT NULL,
    security_answer_3 character varying(255) NOT NULL,
    security_question_1 character varying(255) NOT NULL,
    security_question_2 character varying(255) NOT NULL,
    security_question_3 character varying(255) NOT NULL,
    password_reset_token character varying(255),
    password_reset_token_created timestamp with time zone
);


ALTER TABLE public.users_customuser OWNER TO bugsenseadmin;

--
-- Name: users_customuser_groups; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.users_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_customuser_groups OWNER TO bugsenseadmin;

--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.users_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.users_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_user_permissions; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.users_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_customuser_user_permissions OWNER TO bugsenseadmin;

--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.users_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_qrcode; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.users_qrcode (
    id bigint NOT NULL,
    qr_data text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    closed_at timestamp with time zone
);


ALTER TABLE public.users_qrcode OWNER TO bugsenseadmin;

--
-- Name: users_qrcode_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.users_qrcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_qrcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_results; Type: TABLE; Schema: public; Owner: bugsenseadmin
--

CREATE TABLE public.users_results (
    id bigint NOT NULL,
    infection_detected boolean,
    species character varying(255) NOT NULL,
    concentration character varying(100) NOT NULL,
    antibiotic character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    qr_code_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(25) NOT NULL
);


ALTER TABLE public.users_results OWNER TO bugsenseadmin;

--
-- Name: users_results_id_seq; Type: SEQUENCE; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE public.users_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Token	6	add_token
22	Can change Token	6	change_token
23	Can delete Token	6	delete_token
24	Can view Token	6	view_token
25	Can add Token	7	add_tokenproxy
26	Can change Token	7	change_tokenproxy
27	Can delete Token	7	delete_tokenproxy
28	Can view Token	7	view_tokenproxy
29	Can add blacklisted token	8	add_blacklistedtoken
30	Can change blacklisted token	8	change_blacklistedtoken
31	Can delete blacklisted token	8	delete_blacklistedtoken
32	Can view blacklisted token	8	view_blacklistedtoken
33	Can add outstanding token	9	add_outstandingtoken
34	Can change outstanding token	9	change_outstandingtoken
35	Can delete outstanding token	9	delete_outstandingtoken
36	Can view outstanding token	9	view_outstandingtoken
37	Can add user	10	add_customuser
38	Can change user	10	change_customuser
39	Can delete user	10	delete_customuser
40	Can view user	10	view_customuser
41	Can add QR Code	11	add_qrcode
42	Can change QR Code	11	change_qrcode
43	Can delete QR Code	11	delete_qrcode
44	Can view QR Code	11	view_qrcode
45	Can add Result	12	add_results
46	Can change Result	12	change_results
47	Can delete Result	12	delete_results
48	Can view Result	12	view_results
49	Can add Institution	13	add_institution
50	Can change Institution	13	change_institution
51	Can delete Institution	13	delete_institution
52	Can view Institution	13	view_institution
53	Can add Doctor	14	add_doctor
54	Can change Doctor	14	change_doctor
55	Can delete Doctor	14	delete_doctor
56	Can view Doctor	14	view_doctor
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-05-04 14:58:44.319861+00	2	test@example.com	1	[{"added": {}}]	10	1
2	2025-05-04 14:59:20.830122+00	2	test@example.com	2	[{"changed": {"fields": ["Full name", "Gender", "Date of birth", "Phone number", "Street", "City", "Postcode", "Country", "Joined date"]}}]	10	1
3	2025-07-07 19:05:04.15867+00	2	test@example.com	2	[{"changed": {"fields": ["Full name"]}}]	10	1
4	2025-07-07 19:28:34.079081+00	3	sarah.johnson@email.com	2	[{"changed": {"fields": ["Email address"]}}]	10	1
5	2025-07-07 20:02:24.361313+00	10	Result for maria.garcia@email.com - Infected (2025-07-07 19:56)	2	[{"changed": {"fields": ["Status"]}}]	12	1
6	2025-07-07 20:02:35.568591+00	9	Result for robert.kim@email.com - No Infection (2025-07-07 19:56)	2	[{"changed": {"fields": ["Status"]}}]	12	1
7	2025-07-07 20:02:48.554123+00	8	Result for james.wilson@email.com - Infected (2025-07-07 19:56)	2	[{"changed": {"fields": ["Status", "Species"]}}]	12	1
8	2025-07-07 22:08:57.542326+00	11	Result for sarah.johnson@email.com - Infected (2025-07-07 20:17)	2	[{"changed": {"fields": ["Status", "Infection Detected"]}}]	12	1
9	2025-07-09 16:07:25.100868+00	10	Result for maria.garcia@email.com - Infected (2025-07-07 19:56)	2	[{"changed": {"fields": ["Species"]}}]	12	1
10	2025-07-09 16:07:40.560328+00	8	Result for james.wilson@email.com - Infected (2025-07-07 19:56)	2	[{"changed": {"fields": ["Species"]}}]	12	1
11	2025-07-09 16:07:54.703225+00	6	Result for jennifer.lee@email.com - Infected (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
12	2025-07-09 16:08:06.497743+00	2	Result for michael.chen@email.com - Infected (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
13	2025-07-09 16:08:16.275448+00	1	Result for emily.rodriguez@email.com - Infected (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
14	2025-07-10 21:05:57.777971+00	3	Result for sarah.johnson@email.com - No Infection (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
15	2025-07-10 21:06:08.193723+00	9	Result for robert.kim@email.com - No Infection (2025-07-07 19:56)	2	[{"changed": {"fields": ["Species"]}}]	12	1
16	2025-07-10 21:06:14.605676+00	7	Result for christopher.brown@email.com - No Infection (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
17	2025-07-10 21:06:27.099996+00	5	Result for lisa.wang@email.com - No Infection (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
18	2025-07-10 21:06:34.424503+00	4	Result for david.thompson@email.com - No Infection (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
19	2025-07-10 21:13:28.501459+00	14	Result for sarah.johnson@email.com - Infected (2025-07-10 21:08)	2	[{"changed": {"fields": ["Status"]}}]	12	1
20	2025-07-10 21:16:11.588099+00	14	Result for sarah.johnson@email.com - Infected (2025-07-10 21:08)	2	[{"changed": {"fields": ["Status"]}}]	12	1
21	2025-07-10 21:18:48.97708+00	3	Result for sarah.johnson@email.com - No Infection (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
22	2025-07-10 21:18:57.194444+00	4	Result for david.thompson@email.com - No Infection (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
23	2025-07-10 21:19:04.611415+00	5	Result for lisa.wang@email.com - No Infection (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
24	2025-07-10 21:19:27.092161+00	7	Result for christopher.brown@email.com - No Infection (2025-07-07 19:49)	2	[{"changed": {"fields": ["Species"]}}]	12	1
25	2025-07-10 21:19:34.52649+00	9	Result for robert.kim@email.com - No Infection (2025-07-07 19:56)	2	[{"changed": {"fields": ["Species"]}}]	12	1
26	2025-07-10 21:19:42.065102+00	13	Result for sarah.johnson@email.com - No Infection (2025-07-09 22:43)	2	[{"changed": {"fields": ["Species"]}}]	12	1
27	2025-07-10 21:19:59.947435+00	14	Result for sarah.johnson@email.com - Infected (2025-07-10 21:08)	2	[{"changed": {"fields": ["Species", "Concentration"]}}]	12	1
28	2025-07-10 21:21:25.709314+00	14	Result for sarah.johnson@email.com - Infected (2025-07-10 21:08)	2	[{"changed": {"fields": ["Status"]}}]	12	1
29	2025-07-10 21:43:17.460115+00	2	test@example.com	2	[{"changed": {"fields": ["password"]}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	authtoken	token
7	authtoken	tokenproxy
8	token_blacklist	blacklistedtoken
9	token_blacklist	outstandingtoken
10	users	customuser
11	users	qrcode
12	users	results
13	institutions	institution
14	institutions	doctor
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-05-04 14:42:12.47474+00
2	contenttypes	0002_remove_content_type_name	2025-05-04 14:42:12.47762+00
3	auth	0001_initial	2025-05-04 14:42:12.499195+00
4	auth	0002_alter_permission_name_max_length	2025-05-04 14:42:12.501733+00
5	auth	0003_alter_user_email_max_length	2025-05-04 14:42:12.504447+00
6	auth	0004_alter_user_username_opts	2025-05-04 14:42:12.507429+00
7	auth	0005_alter_user_last_login_null	2025-05-04 14:42:12.510385+00
8	auth	0006_require_contenttypes_0002	2025-05-04 14:42:12.511336+00
9	auth	0007_alter_validators_add_error_messages	2025-05-04 14:42:12.51418+00
10	auth	0008_alter_user_username_max_length	2025-05-04 14:42:12.517082+00
11	auth	0009_alter_user_last_name_max_length	2025-05-04 14:42:12.520715+00
12	auth	0010_alter_group_name_max_length	2025-05-04 14:42:12.52405+00
13	auth	0011_update_proxy_permissions	2025-05-04 14:42:12.52657+00
14	auth	0012_alter_user_first_name_max_length	2025-05-04 14:42:12.529161+00
15	users	0001_initial	2025-05-04 14:42:12.553997+00
16	admin	0001_initial	2025-05-04 14:42:12.56303+00
17	admin	0002_logentry_remove_auto_add	2025-05-04 14:42:12.566906+00
18	admin	0003_logentry_add_action_flag_choices	2025-05-04 14:42:12.570592+00
19	authtoken	0001_initial	2025-05-04 14:42:12.578832+00
20	authtoken	0002_auto_20160226_1747	2025-05-04 14:42:12.592644+00
21	authtoken	0003_tokenproxy	2025-05-04 14:42:12.594014+00
22	authtoken	0004_alter_tokenproxy_options	2025-05-04 14:42:12.596203+00
23	sessions	0001_initial	2025-05-04 14:42:12.601641+00
24	token_blacklist	0001_initial	2025-05-04 14:42:12.618159+00
25	token_blacklist	0002_outstandingtoken_jti_hex	2025-05-04 14:42:12.62282+00
26	token_blacklist	0003_auto_20171017_2007	2025-05-04 14:42:12.63006+00
27	token_blacklist	0004_auto_20171017_2013	2025-05-04 14:42:12.637448+00
28	token_blacklist	0005_remove_outstandingtoken_jti	2025-05-04 14:42:12.642621+00
29	token_blacklist	0006_auto_20171017_2113	2025-05-04 14:42:12.647855+00
30	token_blacklist	0007_auto_20171017_2214	2025-05-04 14:42:12.660225+00
31	token_blacklist	0008_migrate_to_bigautofield	2025-05-04 14:42:12.685767+00
32	token_blacklist	0010_fix_migrate_to_bigautofield	2025-05-04 14:42:12.694643+00
33	token_blacklist	0011_linearizes_history	2025-05-04 14:42:12.695859+00
34	token_blacklist	0012_alter_outstandingtoken_user	2025-05-04 14:42:12.700437+00
35	users	0002_remove_customuser_username	2025-05-04 14:42:12.705202+00
36	users	0003_alter_customuser_managers	2025-05-04 14:42:12.710451+00
37	users	0004_alter_customuser_phone_number	2025-05-04 14:42:12.717539+00
38	users	0005_alter_customuser_gender	2025-05-04 14:42:12.722224+00
39	users	0006_customuser_joined	2025-05-04 14:42:12.728194+00
40	users	0007_remove_customuser_joined_and_more	2025-05-04 14:42:12.7416+00
41	institutions	0001_initial	2025-07-07 19:03:56.684173+00
42	users	0008_customuser_assigned_doctor	2025-07-07 19:03:56.696665+00
43	users	0009_customuser_is_doctor	2025-07-07 19:03:56.705737+00
44	users	0010_qrcode	2025-07-07 19:03:56.721906+00
45	users	0011_remove_qrcode_updated_at	2025-07-07 19:03:56.730399+00
46	users	0012_results	2025-07-07 19:03:56.758563+00
47	users	0013_qrcode_closed_at_results_status	2025-07-07 19:03:56.773445+00
48	users	0014_alter_results_infection_detected	2025-07-07 19:03:56.781552+00
49	users	0015_customuser_security_answer_1_and_more	2025-07-07 19:03:56.8287+00
50	users	0016_hash_existing_security_answers	2025-07-07 19:03:56.840434+00
51	users	0017_customuser_password_reset_token_and_more	2025-07-07 19:03:56.861871+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
v6pcoymlyrdee65vnozz6cxcq2to2dce	.eJxVjEEOwiAQRe_C2hCGMlBcuvcMZIBBqoYmpV0Z765NutDtf-_9lwi0rTVsnZcwZXEWIE6_W6T04LaDfKd2m2Wa27pMUe6KPGiX1znz83K4fweVev3WyiWbkU0CZTVrhIRmsFhGUB4KWJdJDRqdJUi6gCHt9UgRnWdvgVi8P7dRNtY:1uBan0:gpgXqkvi9hEYmIbfh7EObEMqXRuI-6-pAUxepEoeJrY	2025-05-18 14:57:58.743831+00
n2jvplw0prmkfc5gf6jfb2s8omfzsmcj	.eJxVjEEOwiAQRe_C2hCGMlBcuvcMZIBBqoYmpV0Z765NutDtf-_9lwi0rTVsnZcwZXEWIE6_W6T04LaDfKd2m2Wa27pMUe6KPGiX1znz83K4fweVev3WyiWbkU0CZTVrhIRmsFhGUB4KWJdJDRqdJUi6gCHt9UgRnWdvgVi8P7dRNtY:1uZ8Qn:4GzKN94ll6qY6NcUY-jOw6-xc_aGA96-GEcIiF59flc	2025-07-22 13:32:21.774584+00
12cq6863joyfph8d34wrew20ka7gj299	.eJxVjDsOwjAUBO_iGll-D8dxKOlzBmv9IwFkS3FSIe4OkVJAuzOzL-GwrZPbWlrcHMVFkDj9bh7hkcoO4h3lVmWoZV1mL3dFHrTJscb0vB7u38GENn1rkLGG8wBiAgejVJ-T1_6cEG0I1mYFE7XpANYM9p4YRMTdkEKve_H-AOe8N9w:1uZXJi:E9QL1opekCNtIShI9ZCvNeQevyFwgBuKHJ-qr34MiU0	2025-07-23 16:06:42.779254+00
ccg0jkpufqv4wa8jh3okqyjka1ye393x	.eJxVjEEOwiAQRe_C2hAoUwou3XsGMsNMpWpoUtqV8e7apAvd_vfef6mE21rS1mRJE6uzsur0uxHmh9Qd8B3rbdZ5rusykd4VfdCmrzPL83K4fwcFW_nWfUTnTccWHFHMTMb1g0Tv0IGHzo6BmE3MOKCMxAjBWwmWgkGAHFC9P93oOCM:1uZz2z:1wOYooFPihEFOTQRabt-H0wS-frpVgFN_-jshxI6ssE	2025-07-24 21:43:17.469879+00
\.


--
-- Data for Name: institutions_doctor; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.institutions_doctor (customuser_ptr_id, doctor_id, created_at, updated_at, institution_id) FROM stdin;
13	DOC0001	2025-07-07 19:23:22.019692+00	2025-07-07 19:34:21.13724+00	1
14	DOC0002	2025-07-07 19:23:22.401022+00	2025-07-07 19:34:23.408328+00	1
15	DOC0003	2025-07-07 19:23:22.767258+00	2025-07-07 19:34:26.256593+00	2
16	DOC0004	2025-07-07 19:23:23.129313+00	2025-07-07 19:34:28.107682+00	2
\.


--
-- Data for Name: institutions_institution; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.institutions_institution (id, name, address, phone, email, website, created_at, updated_at) FROM stdin;
1	Berlin Medical Center		+49-30-12345678	info@berlinmedical.de	\N	2025-07-07 19:23:21.56643+00	2025-07-07 19:23:21.5665+00
2	Munich Healthcare Institute		+49-89-87654321	contact@munichhealthcare.de	\N	2025-07-07 19:23:21.622541+00	2025-07-07 19:23:21.622554+00
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2025-07-07 19:12:16.709159+00	2
2	2025-07-07 19:16:55.250489+00	3
3	2025-07-07 19:24:24.645426+00	4
4	2025-07-07 22:10:19.862074+00	69
5	2025-07-07 22:11:04.341142+00	70
6	2025-07-09 22:29:02.539378+00	76
7	2025-07-09 22:31:40.242984+00	78
8	2025-07-10 21:43:32.718501+00	84
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0Njk3NTYxOCwiaWF0IjoxNzQ2MzcwODE4LCJqdGkiOiIxYzIxNDk5NWRiZWY0OWY0ODkyOTk0YjY3NDJkZWVjNyIsInVzZXJfaWQiOjJ9.TdI3GVJkJePU6gPIGuwINErX_fha7y5egyyPxhF1ZjQ	2025-05-04 15:00:18.301949+00	2025-05-11 15:00:18+00	2	1c214995dbef49f4892994b6742deec7
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMDA3MCwiaWF0IjoxNzUxOTE1MjcwLCJqdGkiOiIyZTM2MzE0YzljNGE0YTM2ODc0YjA5ZmZiMzJhZjkzNyIsInVzZXJfaWQiOjN9.daeKbmzYqwjzbZhOulQgYxBCL14nusLrWdD2vEX24Ig	2025-07-07 19:07:50.644374+00	2025-07-14 19:07:50+00	3	2e36314c9c4a4a36874b09ffb32af937
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMDM2MCwiaWF0IjoxNzUxOTE1NTYwLCJqdGkiOiI4NGM5Yzg5OTE0YTM0ZmUwYmU4NDM2Y2JlZWVhZTY1ZSIsInVzZXJfaWQiOjR9.XUAGZWHIEAQtNnX3_92GAtcz2J2EkmJnagRoQZh6IO0	2025-07-07 19:12:40.081732+00	2025-07-14 19:12:40+00	4	84c9c89914a34fe0be8436cbeeeae65e
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMDYzNiwiaWF0IjoxNzUxOTE1ODM2LCJqdGkiOiJhMzQxM2QyNzZkN2E0ZDc3OGVkOTRiNzBjNzBmZDgwZCIsInVzZXJfaWQiOjV9.SLJs4ZERHvwzzikP7PHVoMT0XzhtG5S5NgZkUhJWRL0	2025-07-07 19:17:16.91656+00	2025-07-14 19:17:16+00	5	a3413d276d7a4d778ed94b70c70fd80d
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMTAwMiwiaWF0IjoxNzUxOTE2MjAyLCJqdGkiOiI0MmI5YTAzMjgzZTY0MzFhYjg5NWViNWUwOTc1ZjBlNCIsInVzZXJfaWQiOjEzfQ.BkMmqgB44Xcd0m83Rin7Sc-_sU8Bti2XzvxsKDfzPH0	2025-07-07 19:23:22.020987+00	2025-07-14 19:23:22+00	13	42b9a03283e6431ab895eb5e0975f0e4
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMTAwMiwiaWF0IjoxNzUxOTE2MjAyLCJqdGkiOiI3MzQ3OTAxM2ZkNGI0NjE4OGZmOTMwZWI1Y2ZlZTJlNSIsInVzZXJfaWQiOjE0fQ.UZAKnD8aaMeIO0cMlBg8YKAxA2yOwaphwsEBkTEhuvQ	2025-07-07 19:23:22.402486+00	2025-07-14 19:23:22+00	14	73479013fd4b46188ff930eb5cfee2e5
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMTAwMiwiaWF0IjoxNzUxOTE2MjAyLCJqdGkiOiI2NTZkNmI0OGQ1ODk0ZGJhOTVkNzk5NTczZDI3ODRiNyIsInVzZXJfaWQiOjE1fQ.XiPWNhA-72Zpt0iL2in-_of4wHQITy_wKqNqnlD8S0w	2025-07-07 19:23:22.768459+00	2025-07-14 19:23:22+00	15	656d6b48d5894dba95d799573d2784b7
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMTAwMywiaWF0IjoxNzUxOTE2MjAzLCJqdGkiOiJhMTBlOGMzZjhlMDY0M2M3ODJjZjBiY2E2NzQ2OTJmNiIsInVzZXJfaWQiOjE2fQ.MLVjuErD8D-BfSqiCgBgyEsFTfGepdlGRMqcu-83zxk	2025-07-07 19:23:23.130141+00	2025-07-14 19:23:23+00	16	a10e8c3f8e0643c782cf0bca674692f6
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMTA3OCwiaWF0IjoxNzUxOTE2Mjc4LCJqdGkiOiJjNjViY2U4YjFmM2U0MWUwYTU3YjZjMzJhYTQ1ODk0YyIsInVzZXJfaWQiOjZ9.nRYr4ncdIQwsJGbYDC53sXtePAt7O3I-uqWM7yPpbpM	2025-07-07 19:24:38.3021+00	2025-07-14 19:24:38+00	6	c65bce8b1f3e41e0a57b6c32aa45894c
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE1MSwiaWF0IjoxNzUxOTE3MzUxLCJqdGkiOiJjZTAxYzJhZTJhMTA0OWIyYjI5OTM2N2YyMjdmNGMwYyIsInVzZXJfaWQiOjEzfQ.Pnkb8qMi2nFD9t18b2j5Y2UM23xrcjrADmMe80Z1JD4	2025-07-07 19:42:31.110164+00	2025-07-14 19:42:31+00	13	ce01c2ae2a1049b2b299367f227f4c0c
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE1MSwiaWF0IjoxNzUxOTE3MzUxLCJqdGkiOiI0Y2E0ZTgwYjVlZDM0NDdlOGEyOTAwNDFmMTgxOGRjZCIsInVzZXJfaWQiOjE0fQ.UMlkfGvrfwulENnyAEARsRm_Zr8-H61jB9WzZpTrKSQ	2025-07-07 19:42:31.536124+00	2025-07-14 19:42:31+00	14	4ca4e80b5ed3447e8a290041f1818dcd
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE1MSwiaWF0IjoxNzUxOTE3MzUxLCJqdGkiOiJiZDNlMWFmODkyZmU0OGVlYjA1YzEzYWFhODUwOGRhZSIsInVzZXJfaWQiOjE1fQ.zsCRl9wUTOR3-OqzkLbGNYEqc6kK7jo3AntC-d8G8ag	2025-07-07 19:42:31.981602+00	2025-07-14 19:42:31+00	15	bd3e1af892fe48eeb05c13aaa8508dae
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE1MiwiaWF0IjoxNzUxOTE3MzUyLCJqdGkiOiJmNmUwMDQ3NjAyNzU0N2UxYmYxOGFkODliMDRjMmExOSIsInVzZXJfaWQiOjE2fQ.JlMAVPVooa9GEE7m4uG9XjiWZxqaYfwQQVOiP8LAijQ	2025-07-07 19:42:32.483761+00	2025-07-14 19:42:32+00	16	f6e00476027547e1bf18ad89b04c2a19
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE3MCwiaWF0IjoxNzUxOTE3MzcwLCJqdGkiOiI5Zjc1ODc3Y2VjMDk0MDI5YTU3ZTc5OTY1ZDNjZmViZCIsInVzZXJfaWQiOjEzfQ.QUBiuN03RD7_Ih39DnZbjd2F7x45uxFzcCgZafziedk	2025-07-07 19:42:50.266716+00	2025-07-14 19:42:50+00	13	9f75877cec094029a57e79965d3cfebd
15	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE5MywiaWF0IjoxNzUxOTE3MzkzLCJqdGkiOiI1MDFiYjNmNzAyODA0MjlmOTg0MDc5MzQ0YTAwMTliYiIsInVzZXJfaWQiOjEzfQ._1Sysn6y_eshq_Acd8ld9beQ4iSaiHt_eVW7UDl4TEQ	2025-07-07 19:43:13.832314+00	2025-07-14 19:43:13+00	13	501bb3f70280429f984079344a0019bb
16	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE5NCwiaWF0IjoxNzUxOTE3Mzk0LCJqdGkiOiJlMTBlZGIyOGE5MDA0ZTU5ODdmNDJiZTExZmU3ZjFiMCIsInVzZXJfaWQiOjE0fQ.XZpYadc6jsNJ03nsMvDlFhS6SrmkaQzusgERCZ9_EF8	2025-07-07 19:43:14.27895+00	2025-07-14 19:43:14+00	14	e10edb28a9004e5987f42be11fe7f1b0
17	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE5NCwiaWF0IjoxNzUxOTE3Mzk0LCJqdGkiOiJkMGFmNjU2ZjI3NWI0NjIxYTJiZjQ0NGY3OTE4YzZjZSIsInVzZXJfaWQiOjE1fQ.kutAmGiSqPBc_KIrcQgyz24EQkiC3fWnFzXr7ET5kZU	2025-07-07 19:43:14.676776+00	2025-07-14 19:43:14+00	15	d0af656f275b4621a2bf444f7918c6ce
18	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjE5NSwiaWF0IjoxNzUxOTE3Mzk1LCJqdGkiOiJmNjA0ZGE1YzA1YzE0MmU1OTdiYzNiNzM4YjcxODk2ZiIsInVzZXJfaWQiOjE2fQ.fHatbH-NQqbJ5CYRuTqOW6B9VVgJ-JkEX4bVTqStvxI	2025-07-07 19:43:15.117577+00	2025-07-14 19:43:15+00	16	f604da5c05c142e597bc3b738b71896f
19	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjIzMiwiaWF0IjoxNzUxOTE3NDMyLCJqdGkiOiJhOWYzNmUyNjE0NTE0YWY4YTg0M2E5MDAxYTBkNTZhMiIsInVzZXJfaWQiOjEzfQ.27D9a1QtIqLVc5gOl23GVi1RPk3Jo5TxcaGroqdWjc8	2025-07-07 19:43:52.108988+00	2025-07-14 19:43:52+00	13	a9f36e2614514af8a843a9001a0d56a2
20	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjIzMiwiaWF0IjoxNzUxOTE3NDMyLCJqdGkiOiI2N2U2OGU5MmZmMGQ0YmQyYjBiMmI1YzQyZTRiNGIyYiIsInVzZXJfaWQiOjE0fQ.r_N0EDJA7jC0KsIQQ7463A0jjgD_Xu-cEyAasLWbS9s	2025-07-07 19:43:52.568742+00	2025-07-14 19:43:52+00	14	67e68e92ff0d4bd2b0b2b5c42e4b4b2b
21	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjIzMiwiaWF0IjoxNzUxOTE3NDMyLCJqdGkiOiI0ZTc0NWJlNzVmM2E0M2FkOGM1Y2NjZDg1NzI3ZmY1NyIsInVzZXJfaWQiOjE1fQ.WhaDphBOHYVxOkjom5mwBtnA5FbJLpHlrxpWQphQFtI	2025-07-07 19:43:52.97237+00	2025-07-14 19:43:52+00	15	4e745be75f3a43ad8c5cccd85727ff57
22	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjIzMywiaWF0IjoxNzUxOTE3NDMzLCJqdGkiOiI3ZWIxNjMxNTQ1ZTQ0YWJlYmFiMDIxYjk2MzA0OTQ4ZiIsInVzZXJfaWQiOjE2fQ.O1RMU51dpAfc3ho0LbsOFjCrHxwVDGToDJArT2yTYIY	2025-07-07 19:43:53.409481+00	2025-07-14 19:43:53+00	16	7eb1631545e44abebab021b96304948f
23	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjI1OSwiaWF0IjoxNzUxOTE3NDU5LCJqdGkiOiIwZDEwMzBkNGM4NTI0ZDkwOTVhYzhiNDA4Y2NkNTFiYiIsInVzZXJfaWQiOjEzfQ.P2hSvvfWUA1x6Pf-4FkqBwB6vjEkCzWPwFuauZWoE4c	2025-07-07 19:44:19.413985+00	2025-07-14 19:44:19+00	13	0d1030d4c8524d9095ac8b408ccd51bb
24	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjMwNSwiaWF0IjoxNzUxOTE3NTA1LCJqdGkiOiIzNTE1Nzg4YmQzODk0OWJkOTg5NzUyZWY4YzlmZGUxMSIsInVzZXJfaWQiOjEzfQ.sbWgH2EO3ibXW_we6r6pGNFTSFuqqqydU853r7PpEJ4	2025-07-07 19:45:05.387316+00	2025-07-14 19:45:05+00	13	3515788bd38949bd989752ef8c9fde11
25	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjMwNSwiaWF0IjoxNzUxOTE3NTA1LCJqdGkiOiJhYWM4ODc3MjAzMjY0Njg0YTg4N2ZjMGNmMTc2MTc3ZCIsInVzZXJfaWQiOjE0fQ.PvPWx5NHCIsJHhwGjEC8hA2BpGnimT0P_qNffeQwN9w	2025-07-07 19:45:05.906521+00	2025-07-14 19:45:05+00	14	aac8877203264684a887fc0cf176177d
26	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjMwNiwiaWF0IjoxNzUxOTE3NTA2LCJqdGkiOiI4ODZkZjBjNmU1OTU0MjgyYjk4OWFiZWQ4MTkyNThjNyIsInVzZXJfaWQiOjE1fQ.hrypkn_EclUB6Khs_Z_RPAD6r39yc4wmjcXckp4jfrc	2025-07-07 19:45:06.359766+00	2025-07-14 19:45:06+00	15	886df0c6e5954282b989abed819258c7
27	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjMwNiwiaWF0IjoxNzUxOTE3NTA2LCJqdGkiOiJjMjVmNThlNmNkYWU0ZTExYmUzNzE0NDUxMGY0MjNlZCIsInVzZXJfaWQiOjE2fQ.H73A_O3fszM8L2iuP-0mNWrM9HLjVctw3MJGf7fmFzs	2025-07-07 19:45:06.909776+00	2025-07-14 19:45:06+00	16	c25f58e6cdae4e11be37144510f423ed
28	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjM3MSwiaWF0IjoxNzUxOTE3NTcxLCJqdGkiOiI0OGZjNWEwNTFlNjM0ZmEwOWJiYjQyN2E3MmE4YWZkOCIsInVzZXJfaWQiOjEzfQ.rZCJXJS38p7daxx-WPUOhy2KfJuhBgFsn6h6q4hyPLQ	2025-07-07 19:46:11.220245+00	2025-07-14 19:46:11+00	13	48fc5a051e634fa09bbb427a72a8afd8
29	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjM3MSwiaWF0IjoxNzUxOTE3NTcxLCJqdGkiOiJkMTcxNGUxNjM2NmY0MGU5OTRhYzgyZmNjMGRkOGI1OCIsInVzZXJfaWQiOjE0fQ.S6KlyYtQ2SalccoboDq4_DkAE4hhKRQo53mVQpjYYEo	2025-07-07 19:46:11.644702+00	2025-07-14 19:46:11+00	14	d1714e16366f40e994ac82fcc0dd8b58
30	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjM3MiwiaWF0IjoxNzUxOTE3NTcyLCJqdGkiOiI3MjMwMTI1Y2JhY2Y0ZThiYjhlYTJkY2Q3NTQwNTI4YyIsInVzZXJfaWQiOjE1fQ.4QWVgI6zmMwTFUgYZQqruQH7xl7qAEyIglB_hAdogPQ	2025-07-07 19:46:12.126344+00	2025-07-14 19:46:12+00	15	7230125cbacf4e8bb8ea2dcd7540528c
31	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjM3MiwiaWF0IjoxNzUxOTE3NTcyLCJqdGkiOiI5MzYxMTRmMjZmMDU0YWRhOWVkM2NjM2M1MmE5YzMyMyIsInVzZXJfaWQiOjE2fQ.MzQ_pljHu4WMhwOPRFIyxoKOqCItp-oO0oSXXczK3Js	2025-07-07 19:46:12.577596+00	2025-07-14 19:46:12+00	16	936114f26f054ada9ed3cc3c52a9c323
32	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjM4MSwiaWF0IjoxNzUxOTE3NTgxLCJqdGkiOiIwZWViMmVjOTU4OGI0MDRiOTZkOTg3YjliNTIxNzkxYSIsInVzZXJfaWQiOjEzfQ.6vcwVWMoMoPX91tgLtEpsqLlKBUv3zTKJmv6PS9U3JU	2025-07-07 19:46:21.232152+00	2025-07-14 19:46:21+00	13	0eeb2ec9588b404b96d987b9b521791a
33	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjM5OCwiaWF0IjoxNzUxOTE3NTk4LCJqdGkiOiI1NmU4MmEyMDNmNzg0OGY5ODAxZjE2OGIwYTk3YWEzZCIsInVzZXJfaWQiOjEzfQ.ENucZ0C4iQnYyIToEA5kkSOVqIy_yyyabWYighDhAKk	2025-07-07 19:46:38.611853+00	2025-07-14 19:46:38+00	13	56e82a203f7848f9801f168b0a97aa3d
34	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjM5OSwiaWF0IjoxNzUxOTE3NTk5LCJqdGkiOiI4OGM4MDkyYjYzODM0ZWY3ODlmNDhjNmU4OTdjYmM3ZSIsInVzZXJfaWQiOjE0fQ.o7YXcagWrcz9GKGtYttkKGnHnsJbLP_uRxgRiISGVEQ	2025-07-07 19:46:39.272829+00	2025-07-14 19:46:39+00	14	88c8092b63834ef789f48c6e897cbc7e
35	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjM5OSwiaWF0IjoxNzUxOTE3NTk5LCJqdGkiOiIyMjIxMGMwMjc5ZTM0OWE3ODc3ODNhMzZjNDZmYzhjMyIsInVzZXJfaWQiOjE1fQ.UOW3svxZXMsX2pcOkr9R5cTX_6HQlCmken5EEEPw2fk	2025-07-07 19:46:39.898192+00	2025-07-14 19:46:39+00	15	22210c0279e349a787783a36c46fc8c3
36	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQwMCwiaWF0IjoxNzUxOTE3NjAwLCJqdGkiOiI2MWNmZDE5OGZjMmE0ZjJiYTY0YjljZDQ4ZDg3MmQwMiIsInVzZXJfaWQiOjE2fQ.Og6m2UKpeGL87STDtBIMORcmFEzCXZ_vFJCuI7e2qFw	2025-07-07 19:46:40.339956+00	2025-07-14 19:46:40+00	16	61cfd198fc2a4f2ba64b9cd48d872d02
37	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQ1OSwiaWF0IjoxNzUxOTE3NjU5LCJqdGkiOiI0Yzk5ZTUyMDZiMDQ0NjAwOTk4ZTAyMDQxZDNlYWE0MyIsInVzZXJfaWQiOjEzfQ.J3SguacfVVQj4zEp-Xe8lLvZ7FFIkdGl6ts1T6ek_ZA	2025-07-07 19:47:39.070615+00	2025-07-14 19:47:39+00	13	4c99e5206b044600998e02041d3eaa43
38	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQ1OSwiaWF0IjoxNzUxOTE3NjU5LCJqdGkiOiI1MzVmZmY4ZDRhMGU0M2MxYmQ0MWFjODJhMzMzYmQ0YiIsInVzZXJfaWQiOjE0fQ.QsPPIzo0vbSGW0jogH9x5nkBha4XaEgLnC0xQ4YIr8M	2025-07-07 19:47:39.845554+00	2025-07-14 19:47:39+00	14	535fff8d4a0e43c1bd41ac82a333bd4b
39	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQ2MCwiaWF0IjoxNzUxOTE3NjYwLCJqdGkiOiI4MTkyY2ZkYjRjMzI0OTZlOTRhMGNkNjQ3NzAxYzRmZSIsInVzZXJfaWQiOjE1fQ.IE6jA73YWMe8QO4YLqXXsz4RnBtc1r9grlzNyIsbL5Q	2025-07-07 19:47:40.595104+00	2025-07-14 19:47:40+00	15	8192cfdb4c32496e94a0cd647701c4fe
40	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQ2MSwiaWF0IjoxNzUxOTE3NjYxLCJqdGkiOiJlMGNkMTI2NWYxNjc0ZTYyOGIwYWUyMDNkMTdlYzYxNCIsInVzZXJfaWQiOjE2fQ.APpqUzT8dTxey9vRDMz8vyDdLMD4ZGkCEbai7p7Q3-Y	2025-07-07 19:47:41.048109+00	2025-07-14 19:47:41+00	16	e0cd1265f1674e628b0ae203d17ec614
41	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQ3NSwiaWF0IjoxNzUxOTE3Njc1LCJqdGkiOiI5NmM4ZTQzMzVjOGY0OTZhODZiMzY0MTk2N2NkZmVjZiIsInVzZXJfaWQiOjEzfQ.fyuDeX5kPaa6wL-XadfmzPWvA1NM6Cr8-CPeU0lk4vg	2025-07-07 19:47:55.886117+00	2025-07-14 19:47:55+00	13	96c8e4335c8f496a86b3641967cdfecf
42	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQ3NiwiaWF0IjoxNzUxOTE3Njc2LCJqdGkiOiJlMGEyOTkxNWJhMTk0YjZmODNjNjdhMmM1MGQ4ZWM4ZiIsInVzZXJfaWQiOjE0fQ.D1vcxlax97oYJYUi6dc66hINqhe8IrvRSQMDOTDrZY8	2025-07-07 19:47:56.630496+00	2025-07-14 19:47:56+00	14	e0a29915ba194b6f83c67a2c50d8ec8f
43	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQ3NywiaWF0IjoxNzUxOTE3Njc3LCJqdGkiOiJlMmNhYjAyN2E5N2E0NGQzYWZjMzIxNTM3MWEzZDkxMSIsInVzZXJfaWQiOjE1fQ.frH4LfDblUEl7l7EpSl-W6FaLLgdsqJMAq6gciglKek	2025-07-07 19:47:57.337927+00	2025-07-14 19:47:57+00	15	e2cab027a97a44d3afc3215371a3d911
44	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjQ3NywiaWF0IjoxNzUxOTE3Njc3LCJqdGkiOiI0ZmJmYjYzNjZkZWU0YTNiOTVkZWVmOGQ4Yzg4YmYzMyIsInVzZXJfaWQiOjE2fQ.uf0F2jVqosDt8YCiUAdm7xic9V7UMZBh44_DjS8BuUk	2025-07-07 19:47:57.776566+00	2025-07-14 19:47:57+00	16	4fbfb6366dee4a3b95deef8d8c88bf33
45	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjUwOCwiaWF0IjoxNzUxOTE3NzA4LCJqdGkiOiIwMTY1YmE3NmVhNmE0YjI0OGFjODkyMmQwYWE4MzA0MCIsInVzZXJfaWQiOjEzfQ.qgXA_gDkwFOAox95NGh670JT6v26BHPa_jGy97qfwN0	2025-07-07 19:48:28.316797+00	2025-07-14 19:48:28+00	13	0165ba76ea6a4b248ac8922d0aa83040
46	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjUwOSwiaWF0IjoxNzUxOTE3NzA5LCJqdGkiOiJhMmY0MzExNmNkMjQ0Mzk0YjFmZjdmZjM1NTIzNzc3NCIsInVzZXJfaWQiOjE0fQ.9xeP_BB5XMfYSwZgBUvTE7o6ZktlcQCwiM7uvbLMdI8	2025-07-07 19:48:29.153646+00	2025-07-14 19:48:29+00	14	a2f43116cd244394b1ff7ff355237774
47	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjUwOSwiaWF0IjoxNzUxOTE3NzA5LCJqdGkiOiJlZDliNzQwOTE2Yjg0NTcwOTBhMGYzMGFhM2JhMmU3NCIsInVzZXJfaWQiOjE1fQ.aCS8UFYD1zWbwTHzivGrRKhabJqlIk8K1XW9Geg54Vc	2025-07-07 19:48:29.903912+00	2025-07-14 19:48:29+00	15	ed9b740916b8457090a0f30aa3ba2e74
48	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjUxMCwiaWF0IjoxNzUxOTE3NzEwLCJqdGkiOiJhZmEwZTljYjE5MDY0ZmY1ODZkMmFkYzUzOTgzNzgzNiIsInVzZXJfaWQiOjE2fQ.Qix8VXBZJoqnMzDqk-TMsMUkZ0evicFr_YfD8HuKqtY	2025-07-07 19:48:30.370599+00	2025-07-14 19:48:30+00	16	afa0e9cb19064ff586d2adc539837836
49	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjU4NCwiaWF0IjoxNzUxOTE3Nzg0LCJqdGkiOiI3ZTAyYjg3NjM2Njg0MWViYTM3OTUyNTAxMGRiOTNkMSIsInVzZXJfaWQiOjEzfQ.LOPLYDKDyegtv6ZEurh6uyXyVCQ0-GK0kBw2cmx92Oc	2025-07-07 19:49:44.484977+00	2025-07-14 19:49:44+00	13	7e02b876366841eba379525010db93d1
50	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjU4NSwiaWF0IjoxNzUxOTE3Nzg1LCJqdGkiOiJiOTFkYTUxZTU2MWE0NjI0OTQ4MzY3YWFlZGY0MjE1NCIsInVzZXJfaWQiOjE0fQ.xyyUl7FiPgHduk4JYd7L0v-mLLWV2dVQZkFBWMOTtIw	2025-07-07 19:49:45.654466+00	2025-07-14 19:49:45+00	14	b91da51e561a4624948367aaedf42154
51	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjU4NiwiaWF0IjoxNzUxOTE3Nzg2LCJqdGkiOiIwNzA3YWM3Y2FjMmI0N2ZiODI0NDNlMmM0NjkyYWRkYiIsInVzZXJfaWQiOjE1fQ.RpcIzjmrui1tTHPK3Mp4VMetHskcLcPOnmfK1gJJXdY	2025-07-07 19:49:46.539382+00	2025-07-14 19:49:46+00	15	0707ac7cac2b47fb82443e2c4692addb
52	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjU4NywiaWF0IjoxNzUxOTE3Nzg3LCJqdGkiOiIwYzJmZmQ2MzhjZWY0YmJhYThlODA5NWI2ZTQzN2EwNSIsInVzZXJfaWQiOjE2fQ.QkmDerQxO1E4-s1s_48EN9I43fVhHhq1xHF8DbwwIgY	2025-07-07 19:49:47.003997+00	2025-07-14 19:49:47+00	16	0c2ffd638cef4bbaa8e8095b6e437a05
53	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjY1MCwiaWF0IjoxNzUxOTE3ODUwLCJqdGkiOiIyZTBmMzE2YmQzN2I0MDZkYTA4N2I5NTFlM2EzMmI5YSIsInVzZXJfaWQiOjE1fQ.7fbi4DtHSMcu70AkVabvR_qnXUZkO5l0tWmRsIDUZWs	2025-07-07 19:50:50.362822+00	2025-07-14 19:50:50+00	15	2e0f316bd37b406da087b951e3a32b9a
54	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMjk4NCwiaWF0IjoxNzUxOTE4MTg0LCJqdGkiOiJiZTYzMGRjYjAzNGQ0NmM0YTkwMTg0YmIwNjM4NWQzYSIsInVzZXJfaWQiOjE1fQ.NQDQIidxVPsHDAROFGZa7GfdIDdDZVyumllZNqBoiOI	2025-07-07 19:56:24.003963+00	2025-07-14 19:56:24+00	15	be630dcb034d46c4a90184bb06385d3a
55	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzA4NSwiaWF0IjoxNzUxOTE4Mjg1LCJqdGkiOiJhNWJjMDg0NjMzZGM0ZmNmYTE2ZGU2ZWViY2U1YzNkYyIsInVzZXJfaWQiOjEzfQ.CAQtwohBzPdL1XGWaFa-gc1OhhfW_i0xCxc0L4UeUhs	2025-07-07 19:58:05.387039+00	2025-07-14 19:58:05+00	13	a5bc084633dc4fcfa16de6eebce5c3dc
56	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzA5OCwiaWF0IjoxNzUxOTE4Mjk4LCJqdGkiOiJlNTQ1MThkODY2Nzc0ZTJiYTllYjcwMWZjM2EwMGRmNSIsInVzZXJfaWQiOjE0fQ.8mH9QXYEb46CEalR72w-kZb9E16Lk3n4SZOIfC_-y2g	2025-07-07 19:58:18.90846+00	2025-07-14 19:58:18+00	14	e54518d866774e2ba9eb701fc3a00df5
57	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzExMCwiaWF0IjoxNzUxOTE4MzEwLCJqdGkiOiIwNmNjMDljNGQ2YTY0ZjA1OTkwNjA1MDhiMzZkODk4NCIsInVzZXJfaWQiOjEzfQ.z7Nssq0zaH9dkoTJ__c1-6JCwy1B092nzEoLBiZ3nZM	2025-07-07 19:58:30.085242+00	2025-07-14 19:58:30+00	13	06cc09c4d6a64f0599060508b36d8984
58	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE2MywiaWF0IjoxNzUxOTE4MzYzLCJqdGkiOiJiZjA3YTQ1MDZkMWE0ZDYwYjI4YjI2NjY2ODE5NzI5MyIsInVzZXJfaWQiOjEzfQ.SWLSRcv2moX6hw0S9MkZ6tP8v7KsT6WR3QBYK2LvuWE	2025-07-07 19:59:23.238378+00	2025-07-14 19:59:23+00	13	bf07a4506d1a4d60b28b266668197293
59	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE2MywiaWF0IjoxNzUxOTE4MzYzLCJqdGkiOiI2ZjYwMzQwOTYxY2M0OWY4YTNjNDJhZDQyOTg2Y2ZhNiIsInVzZXJfaWQiOjEzfQ.y3zAaPintUjjGxsDhEmcZz3TvQjkspicaorwPdesv1c	2025-07-07 19:59:23.670929+00	2025-07-14 19:59:23+00	13	6f60340961cc49f8a3c42ad42986cfa6
60	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE2NCwiaWF0IjoxNzUxOTE4MzY0LCJqdGkiOiI0YzEwMGUwZDQ3MmI0MDkzODg1ZmNkMjQ3YjUxYjRhYSIsInVzZXJfaWQiOjEzfQ.77FPyImOD3k6sSorIjFQW0cPWy7MARG2hHFS0eq8SDE	2025-07-07 19:59:24.090498+00	2025-07-14 19:59:24+00	13	4c100e0d472b4093885fcd247b51b4aa
61	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE2NCwiaWF0IjoxNzUxOTE4MzY0LCJqdGkiOiJkYzAxYjRjZDRlNzc0Y2QxOTkxMWVjZDIwYWZiN2ZhMSIsInVzZXJfaWQiOjEzfQ.K0Eswneu_dek7-Vnfq3ATOhmhm5apu6uu8e5rn0O_4c	2025-07-07 19:59:24.493036+00	2025-07-14 19:59:24+00	13	dc01b4cd4e774cd19911ecd20afb7fa1
62	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE3NywiaWF0IjoxNzUxOTE4Mzc3LCJqdGkiOiJhMDJjNGQ1MDI5MmE0YjM1OTQ2NmFjMWM1MWNkZmM0MCIsInVzZXJfaWQiOjEzfQ.X_V_vP_izviE3hHRajMVDzcOEqaK6bUxuhR5y3LMssc	2025-07-07 19:59:37.262218+00	2025-07-14 19:59:37+00	13	a02c4d50292a4b359466ac1c51cdfc40
63	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE3NywiaWF0IjoxNzUxOTE4Mzc3LCJqdGkiOiIwZDhhZGE2MTQyNTc0ZWZkODAzMDAwZTkwYTkyZDEwMCIsInVzZXJfaWQiOjEzfQ.-jLYTJTq4FZrU5QOyaHe9DnPr3vadv9cf2VNwvsqjNQ	2025-07-07 19:59:37.662163+00	2025-07-14 19:59:37+00	13	0d8ada6142574efd803000e90a92d100
64	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE3OCwiaWF0IjoxNzUxOTE4Mzc4LCJqdGkiOiJjYTUyODk1ZTE1MWU0NzI0YWU4OGM3MjY5OGEzNDYxNSIsInVzZXJfaWQiOjEzfQ.uW9QufkJi3G-Hrcq6wA2eBe48Co9uCJTVXZssJUg2UE	2025-07-07 19:59:38.080007+00	2025-07-14 19:59:38+00	13	ca52895e151e4724ae88c72698a34615
65	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE3OCwiaWF0IjoxNzUxOTE4Mzc4LCJqdGkiOiI1NDAwMDIzMDQ5NWU0NzFhOTllNGY2NGIyMWZjNjY2NSIsInVzZXJfaWQiOjEzfQ.8HxVEouN6HFWBVngpS8gBaYxJzZ_g2fiMnA7ZXmQVjQ	2025-07-07 19:59:38.478698+00	2025-07-14 19:59:38+00	13	54000230495e471a99e4f64b21fc6665
66	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyMzE3OCwiaWF0IjoxNzUxOTE4Mzc4LCJqdGkiOiJmZGFlNjY2MWU0NWM0MGNlODQ4NDE1OTllMWRhNWU4OSIsInVzZXJfaWQiOjEzfQ.qYQHY830C59K8F0nXImgXa4WkebyqZ7NgUZdPdfkcZ0	2025-07-07 19:59:38.987096+00	2025-07-14 19:59:38+00	13	fdae6661e45c40ce84841599e1da5e89
67	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyNDI2MSwiaWF0IjoxNzUxOTE5NDYxLCJqdGkiOiI0N2NlY2U3NDJjYjg0ZTdkOGM3ZGMwYWRhMzRjZGZkZiIsInVzZXJfaWQiOjEzfQ.2dxnAAcKbSt2ZIRrbXmXjLH_m888nnrouXkMaE_Evzo	2025-07-07 20:17:41.442449+00	2025-07-14 20:17:41+00	13	47cece742cb84e7d8c7dc0ada34cdfdf
68	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUyNDI4OCwiaWF0IjoxNzUxOTE5NDg4LCJqdGkiOiIxNTAwYjhlOWZlNmM0NGUxOGZiZDM2NzY0YWNkMWMwNyIsInVzZXJfaWQiOjEzfQ._1qs9Ec3raJ-zQm3j_8T4FnZ2NiRmFAN1gKsZ-AsZ9k	2025-07-07 20:18:08.665436+00	2025-07-14 20:18:08+00	13	1500b8e9fe6c44e18fbd36764acd1c07
69	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUzMDk5NiwiaWF0IjoxNzUxOTI2MTk2LCJqdGkiOiI1ZmNkMWQ5MDYyNzI0NzAwYTE5YjhjNDI2NGU5YWJjNiIsInVzZXJfaWQiOjN9.65qrwXKvUsjLmbqG_PsJvS3RI9ZnmlV1M0lx0vmu0DU	2025-07-07 22:09:56.624666+00	2025-07-14 22:09:56+00	3	5fcd1d9062724700a19b8c4264e9abc6
70	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjUzMTA1MCwiaWF0IjoxNzUxOTI2MjUwLCJqdGkiOiJkOGQ2NWMxMDZlZTg0MTRjYTkxMGIwZWNjYjUwNzUyYyIsInVzZXJfaWQiOjEzfQ.U-sbnpaO_aD-H5NwOngcrNyWSueXyt70LkGryhPhl50	2025-07-07 22:10:50.976427+00	2025-07-14 22:10:50+00	13	d8d65c106ee8414ca910b0eccb50752c
71	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjYxMzcwNCwiaWF0IjoxNzUyMDA4OTA0LCJqdGkiOiI3YThlZDJjNDM4ZDA0ZjhiYjNjNGRkZjllOWE4NWMyYSIsInVzZXJfaWQiOjJ9.1434JdwDhsocnShGhDkon17JWvBb-w3V97WPdsI1mxU	2025-07-08 21:08:24.054504+00	2025-07-15 21:08:24+00	2	7a8ed2c438d04f8bb3c4ddf9e9a85c2a
72	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjYxMzczMywiaWF0IjoxNzUyMDA4OTMzLCJqdGkiOiIwYjdkY2U0MGNjZTQ0MTBlYTZjNzUzYjg5ZDQzY2QyMyIsInVzZXJfaWQiOjJ9.nwYKF6f4yEcHycdGnpxnuaCn4Sir_8-OfbV7iZvWbtA	2025-07-08 21:08:53.133282+00	2025-07-15 21:08:53+00	2	0b7dce40cce4410ea6c753b89d43cd23
73	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjYxNDUwNSwiaWF0IjoxNzUyMDA5NzA1LCJqdGkiOiIwMDFhYWY2MTEzMTM0N2IzODZiOTJjM2U0YTMwNWQxNCIsInVzZXJfaWQiOjN9.KDSvHPM7KypOjPDSiHRXVIrCcwYsFJqQNwj79UIoU8w	2025-07-08 21:21:45.496871+00	2025-07-15 21:21:45+00	3	001aaf61131347b386b92c3e4a305d14
74	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjYxNDcwMywiaWF0IjoxNzUyMDA5OTAzLCJqdGkiOiJkYjI0Mjk5ZWNlNGU0ODQzOTAxNWNhMmVjZDA4YWQ0MyIsInVzZXJfaWQiOjN9.FcGt37QXFKHc5Lav3Jy39Up_VGTksaJNeMvoWRYN-hg	2025-07-08 21:25:03.055577+00	2025-07-15 21:25:03+00	3	db24299ece4e48439015ca2ecd08ad43
75	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjcwNDU4NywiaWF0IjoxNzUyMDk5Nzg3LCJqdGkiOiI5ODM4NzYwNDA2MGM0YTg4OTliMjhhMjI2YmY2NTdlYSIsInVzZXJfaWQiOjEzfQ.9mqmD9EIvwmBs3B8-ogVJAv1h9AGzHw-NrIUF8zg1Ps	2025-07-09 22:23:07.985251+00	2025-07-16 22:23:07+00	13	98387604060c4a8899b28a226bf657ea
76	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjcwNDkxNSwiaWF0IjoxNzUyMTAwMTE1LCJqdGkiOiI5MzgzNDNhNTliZjk0ZDdlOGJhZTRmYjQ5MGY5NDViMyIsInVzZXJfaWQiOjEzfQ.NhOk966d5zoYZKt0qW3zE7CMGsUDld9rUMWL0QVDhjo	2025-07-09 22:28:35.144595+00	2025-07-16 22:28:35+00	13	938343a59bf94d7e8bae4fb490f945b3
77	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjcwNTAyOSwiaWF0IjoxNzUyMTAwMjI5LCJqdGkiOiJmZTg1MDdhZDAzYjQ0NDM3ODVhNmY5NDgwMjkzZTk1MCIsInVzZXJfaWQiOjEzfQ.JL9rwSEQ4QRLCXfsWa4gj1Cckj2kshYhblHSVWBtiw4	2025-07-09 22:30:29.639942+00	2025-07-16 22:30:29+00	13	fe8507ad03b4443785a6f9480293e950
78	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjcwNTAzNiwiaWF0IjoxNzUyMTAwMjM2LCJqdGkiOiIyNTllNTJmNTljMDA0MzE3OGE2MmVmOGU0Mjk3ODljMyIsInVzZXJfaWQiOjEzfQ.OYLDq5VMoPyhjIcXUIB8A_oqVXEhdKhfMeakCM_mAFw	2025-07-09 22:30:36.29193+00	2025-07-16 22:30:36+00	13	259e52f59c0043178a62ef8e429789c3
79	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjcwNTExOCwiaWF0IjoxNzUyMTAwMzE4LCJqdGkiOiI1ZTg4OWRhYmE2N2Y0YzZmYmU1OGY5MTljYmRhNWVkNiIsInVzZXJfaWQiOjN9.0c0ZZFyNyfJFUm102EgcfmRHR5MTYMpMFcpMDE3LQQQ	2025-07-09 22:31:58.153719+00	2025-07-16 22:31:58+00	3	5e889daba67f4c6fbe58f919cbda5ed6
80	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Mjc4NTc4OSwiaWF0IjoxNzUyMTgwOTg5LCJqdGkiOiJmNDNkNmQyYzM2ZjM0ZjVlYjFkNTYzMmQ1ODM3ZGU1NCIsInVzZXJfaWQiOjEzfQ.ivyg20ptC1xSK1EUcd0xdoyY6BOGXNiQ-RHbM3MfI2A	2025-07-10 20:56:29.001189+00	2025-07-17 20:56:29+00	13	f43d6d2c36f34f5eb1d5632d5837de54
81	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Mjc4NjI1MywiaWF0IjoxNzUyMTgxNDUzLCJqdGkiOiIwZTM1YzE3NGM4YjI0MmZmYTNlMjNkNDg2OTlmZmY0ZSIsInVzZXJfaWQiOjEzfQ.NnKlxRh2ECdvq9wiqElFRqWsjX4P281oog6HbaHxF68	2025-07-10 21:04:13.626204+00	2025-07-17 21:04:13+00	13	0e35c174c8b242ffa3e23d48699fff4e
82	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Mjc4NjQ4NSwiaWF0IjoxNzUyMTgxNjg1LCJqdGkiOiJjNzM5YjdmM2IyNDY0MTk0OWNmMTZkYmU5MmQxNTViMyIsInVzZXJfaWQiOjN9.a-jlk5-9ZUKG4GcidwfEfWV12KBXPo6YBxOlu5ZyDV8	2025-07-10 21:08:05.1929+00	2025-07-17 21:08:05+00	3	c739b7f3b24641949cf16dbe92d155b3
83	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Mjc4NjY0MiwiaWF0IjoxNzUyMTgxODQyLCJqdGkiOiI5YjdjNDczMmRlMzU0MDAxYjgwMWNmYzllMjg0NjU5NCIsInVzZXJfaWQiOjEzfQ.1_DFRmCdJ3z2Qh9Y4kcAN6wGE8guRQb9j1p-dLLL5Jc	2025-07-10 21:10:42.957466+00	2025-07-17 21:10:42+00	13	9b7c4732de354001b801cfc9e2846594
84	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Mjc4ODYwMCwiaWF0IjoxNzUyMTgzODAwLCJqdGkiOiJkYjhhMTBkNjk5MzU0ZDcyYWJiZTE1MDVkMTlhMWJlNSIsInVzZXJfaWQiOjJ9.F8Ln-6h1YIf8-jns-IIorS-RpM0-JoGINn0UPqahGQ0	2025-07-10 21:43:20.28262+00	2025-07-17 21:43:20+00	2	db8a10d699354d72abbe1505d19a1be5
\.


--
-- Data for Name: users_customuser; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.users_customuser (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, full_name, gender, dob, phone_number, street, city, postcode, country, assigned_doctor_id, is_doctor, security_answer_1, security_answer_2, security_answer_3, security_question_1, security_question_2, security_question_3, password_reset_token, password_reset_token_created) FROM stdin;
13	pbkdf2_sha256$1000000$BKRRfpPqcll0oImyjlyaCR$FbJsoLclP1BFBMjTO4XDWEPRkOnrIxtATpjbA5HBjt8=	\N	f			t	t	\N	anna.schmidt@berlinmedical.de	Dr. Anna Schmidt		\N	+49-30-11112222					\N	t							\N	\N
15	pbkdf2_sha256$1000000$fiJ8XFRNfmuCkfgMYi5Ytu$i5j/FMvSdVHqIWd20JzJTAsQrgtTHdkq2/nCIQLNHGg=	\N	f			t	t	\N	maria.weber@munichhealthcare.de	Dr. Maria Weber		\N	+49-89-55556666					\N	t							\N	\N
14	pbkdf2_sha256$1000000$YwGeBM7dY4EhZxr8JK9tNs$ZDJ65BnMyXFQfPWRHOz1MCMisJd3hnx35rt2k6QJioc=	\N	f			t	t	\N	hans.mueller@berlinmedical.de	Dr. Hans Mueller		\N	+49-30-33334444					\N	t							\N	\N
8	pbkdf2_sha256$1000000$knmJgMJo2dqm1swjxNOKmQ$ZI8Vezk+sI0A4vG/GiSbMoPaTa4SqLtv7Y/1w0MVYzI=	\N	f			f	t	2025-07-07	james.wilson@email.com	James Wilson	Male	1987-12-05	+49-211-44556677	Testweg 987	Düsseldorf	40210	Germany	15	f	pbkdf2_sha256$1000000$1LqtoDzr74SQqiT7jHip7T$cuopUKsJOzppB0Dmao6FDTIONkS40f6OsVL32ZcavX4=	pbkdf2_sha256$1000000$fWqAkJTn403Yzt7l5uOpBO$Mu34SSFhg8gKf2MHJpz4p9B/T1FZPIW134PEwwrPyHY=	pbkdf2_sha256$1000000$1Kk0IDtbJsWvzMGtxcclzP$zhSIGXNzgWwTR7hRbROhqd3gcKZqYcue+rhjooPPUmg=	What was your childhood best friend's name?	What is your favorite ice cream flavor?	What is your lucky number?	\N	\N
5	pbkdf2_sha256$1000000$Wwm14MjRM5g5MYyDpH4kIz$9leiI7taGibVxw5H33XHs8zjdZaWjnhiZ01bG44FMkA=	\N	f			f	t	2025-07-07	emily.rodriguez@email.com	Emily Rodriguez	Female	1995-11-08	+49-40-11223344	Teststraße 789	Hamburg	20095	Germany	13	f	pbkdf2_sha256$1000000$00fsX61pYMY9JouHCvpNDX$7A2t52Q346Rfme8obJvtlr5Z2vDQ9TLvAlGo2qbMALs=	pbkdf2_sha256$1000000$sWNJ1LsL8jBZMZdyJyGyS2$m9gMUwUHX3tu15iflwZggOJNsLRXzjCjmOrPz6OglC8=	pbkdf2_sha256$1000000$p63yXTatvIWEh9Q9N0axof$xfVSv6A76XIo8lf+HJ54MXg0WeuEx0eDhzXQ6jDX20w=	What is your favorite movie?	What street did you grow up on?	What is your favorite food?	\N	\N
16	pbkdf2_sha256$1000000$2oAaSDvKWC2M4KiqoIuFm2$Zyrfk6ekJqMG+fTXP0zwHeb2Wz2bhSRkfcXnIjHkrlM=	\N	f			t	t	\N	klaus.fischer@munichhealthcare.de	Dr. Klaus Fischer		\N	+49-89-77778888					\N	t							\N	\N
10	pbkdf2_sha256$1000000$jYlCXCCZxVJWDby3DtUJip$vg555U6MRnZW4Y5uK7/5++SG632YRi0JYZx6ax/ru44=	\N	f			f	t	2025-07-07	robert.kim@email.com	Robert Kim	Male	1989-01-25	+49-234-22334455	Musterweg 258	Bochum	44787	Germany	15	f	pbkdf2_sha256$1000000$MBkGEOgU0WF4fn5MsQuczp$Cma/1g8QroFFW4B+H1vgVD5AJoEaFHkyy1xQrSsZqHQ=	pbkdf2_sha256$1000000$CrTWFqkVy4nXj6kz1OoqOw$a4K4cQv41yjA0GeYBXySCRGhHGELXXY+ZMMg1mYgBV0=	pbkdf2_sha256$1000000$iIv2c4oEzue5iBHLVVRvyA$5uiAS2kAV58HUVqSo5J3uK79Gva92eXDglRXVm5F0HQ=	What is your favorite band?	What is your favorite animal?	What is your favorite drink?	\N	\N
11	pbkdf2_sha256$1000000$2vFRHfjn9dqF0mSvhCjjDP$LdvAR7kXQxuEDXAZH0FOy9IgcedGug/3nX3m4TUxDLE=	\N	f			f	t	2025-07-07	jennifer.lee@email.com	Jennifer Lee	Female	1991-08-14	+49-231-11223344	Testallee 369	Dortmund	44135	Germany	16	f	pbkdf2_sha256$1000000$OHbWcv9Mq6BRnPm97pt6LU$d5reyYe/c6FqhRXZf7BsvMn0kvN/o2651bVaZ+ZxPNk=	pbkdf2_sha256$1000000$RK6csvKMFGv0lBbZ22bBDu$pZXMYBnqAV1t4T093HYCcbinhF7d5MgDQVqQyX77UHE=	pbkdf2_sha256$1000000$YSE7A3SNsI4dAzcGJVWfxg$rIx/z0/PvjoBZQBUsL2fLpG6IccK4HTHgloYzPhtsBE=	What is your favorite TV show?	What is your favorite dessert?	What is your favorite hobby?	\N	\N
6	pbkdf2_sha256$1000000$ru8G65HYmD8pTqAgqj0vFe$m8PkmXSRaaEaxw0tZxlSgywL+LF0h5NbeBUZv1uIhNQ=	\N	f			f	t	2025-07-07	david.thompson@email.com	David Thompson	Male	1985-04-12	+49-221-55667788	Beispielallee 321	Köln	50667	Germany	14	f	pbkdf2_sha256$1000000$sZFLVIOano51vlbqi3nBJp$w8zKfAu5pI2EoZAHYl5YPJeGrnX7JAHScHXM8vPPG+o=	pbkdf2_sha256$1000000$Mz3QbTgXHxvTFfVXhrzu2t$sSy9dnvX/NyzWqzi9OxCxsebqHfbt/Q7+2/U9AxLeeg=	pbkdf2_sha256$1000000$HLfPOCcvpyLHW09VB8GOiC$/G9QJCxVJxPAjNemiarA8WCUt9ipfqQnsms6HoXjViI=	What was your first car?	What is your favorite sport?	What is your father's middle name?	\N	\N
4	pbkdf2_sha256$1000000$YSprVPOulwlpbyrIf9TcXo$SjySSPISsXC7qes8dW2pnawR9UawyQr6uEQfKQaea0A=	\N	f			f	t	2025-07-07	michael.chen@email.com	Michael Chen	Male	1988-07-22	018987654321	Beispielweg 456	Munich	80331	Germany	13	f	pbkdf2_sha256$1000000$6XSCUcOtfhMQKc4XAKi08K$YbJcr2+qZhEtJalhg5luF4sML/BmtNxaDJl2GIJvnRY=	pbkdf2_sha256$1000000$4slkeXrwlkLtoyzkFLht1W$2KfDfOltMYsj1z7Z38pvXc3UM+Xc8U0mm2kvNyBET10=	pbkdf2_sha256$1000000$h33E40VhK1N6utwdirTN1n$V9DNTqnMXWqeWV4UcgGJA/cFPdrMgiclxvLoK4L3zS8=	What was the name of your first school?	What is your favorite color?	What was your childhood nickname?	\N	\N
7	pbkdf2_sha256$1000000$2Fgj5WK33YUKbWng7qGEr4$Xje4jiEzFueFiSOahoeB8ug50ad+xd1/4ChHQ4s6YEQ=	\N	f			f	t	2025-07-07	lisa.wang@email.com	Lisa Wang	Female	1990-09-30	+49-69-99887766	Musterplatz 654	Frankfurt	60311	Germany	14	f	pbkdf2_sha256$1000000$R5M3AJq22SoZ7GpRzvzSzW$XRxbjgHKaH0o4c34jEuqsRLw0ScCsTddPPftC7v9ess=	pbkdf2_sha256$1000000$oQpDVAUpy3RaVxYh2HYf0y$RZGtFWNspIJoNTsPJbgN4LG2I7L63/Q5P+KIwXKxMJo=	pbkdf2_sha256$1000000$CGE6YoUMNiRrHqSTqyOOyI$bHL+QXmBbh/EwvZjNTrSYlh18uY1dPZviXHpBF/OaVE=	What is your favorite book?	What is your dream vacation destination?	What is your favorite season?	\N	\N
9	pbkdf2_sha256$1000000$WyjHoqdWp49urSgosbK4A1$8t/6L8uugn81jNIso+S1j4PplA0rYBz6zh6yCvx3VsE=	\N	f			f	t	2025-07-07	maria.garcia@email.com	Maria Garcia	Female	1993-06-18	+49-201-33445566	Beispielstraße 147	Essen	45127	Germany	15	f	pbkdf2_sha256$1000000$9R8CczZyJaWev37L3DYOBh$ZYRQlajvOXkea2+vjvPCFCtqpTZeWjVwBOVRXAW8qXE=	pbkdf2_sha256$1000000$UsCnwTS3kjkBvGG4pKbPNU$HVlZoGeS492gbdVy108wtEKKH2Vwim86bt2UbTPj34Y=	pbkdf2_sha256$1000000$m46mfA2SbR5mkfPnQ3yymP$rYokjviOFtomxUNHPLCNUfMpWVWPmfoSGM4+Q09DkiQ=	What is your favorite flower?	What was your first job?	What is your favorite holiday?	\N	\N
12	pbkdf2_sha256$1000000$4lUIuVvpgKzMz6PewEU7xX$yOjCa5PP/I6EXZYZJHB1JWFNDqgzihAlTcF27tZzmmM=	\N	f			f	t	2025-07-07	christopher.brown@email.com	Christopher Brown	Male	1986-10-03	+49-228-55667788	Beispielplatz 741	Bonn	53111	Germany	16	f	pbkdf2_sha256$1000000$oB15O1scyNq56mbxJqddli$2BLcB555X41f7R30b0JoiN9pTMdYxxl5zvlF+eVuYio=	pbkdf2_sha256$1000000$aiTtxTxjO2JOJBowcvSFN0$oPHS3WZqXX9BxhXxiYTv3J45BdRE+tOIT8Ms2I0uo2w=	pbkdf2_sha256$1000000$83EqwIoqnPpdCoZ4X2SaXO$m5ZcBKIf8Kg1OuMbKuqplFQ4PPCLjZGrd/KWY//ZoKE=	What is your favorite restaurant?	What is your favorite game?	What is your favorite subject in school?	\N	\N
1	pbkdf2_sha256$1000000$uPq6S6HuYtuPhfIq8zV77D$4td70F1rcENIBiMuAHiHKMp1+3PZ/HJv0UilzrmMKbQ=	2025-07-10 21:42:57.477014+00	t			t	t	\N	bugsense@admin.com			\N	\N					\N	f							\N	\N
2	pbkdf2_sha256$1000000$riCHj6mnagomJbpymQlFiU$TCcFN/WAcARey7mYCZLV6NorKP5HNG/HAmfUvOOIey4=	\N	f			f	t	2025-05-04	test@example.com	Test User	Other	2025-05-04	01657486372	Eggenfeldner Strasse 55	Pfarrkirchen	84347	Germany	\N	f							\N	\N
3	pbkdf2_sha256$1000000$OEKljxFJl4Ra7I2Z07ckzh$Rj1/UXAXfSZr1WBwcF29pJpIOizG4RUmsAju35BZMAY=	\N	f			f	t	2025-07-07	sarah.johnson@email.com	Sarah Johnson	Female	1992-03-15	015550123	Musterstrasse 123	Berlin	10115	Germany	13	f	pbkdf2_sha256$1000000$0trSzeL7JWzXFLUgiyrgCZ$r69caVnAEJfhlCFrHNdo+7yiTk+vP2YdrubXi2pR7Zg=	pbkdf2_sha256$1000000$NhoRTRMNOFMtpJX3r2H327$cwj6fVrOWdlBaAU/to1ugsyui3AHuaSqCClZ1n9+Iwo=	pbkdf2_sha256$1000000$1vMfRfUChKgdVE6Atw5GCP$nEd3lRyLgUDn1hXdaj6wc3nI9dARYiP88MySpAdSoHY=	What was the name of your first car?	In which city were you born?	What is your mother's maiden name?	1I6lx0xPl3EvbewKBuh23oaaGnMAoSDl1z109GKpvJI	2025-07-08 21:24:13.870777+00
\.


--
-- Data for Name: users_customuser_groups; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.users_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.users_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: users_qrcode; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.users_qrcode (id, qr_data, created_at, user_id, closed_at) FROM stdin;
1	QR_5_1751917784	2025-07-07 19:49:44.808928+00	5	2025-07-07 20:00:50.172695+00
2	QR_4_1751917784	2025-07-07 19:49:44.999668+00	4	2025-07-07 20:00:51.294395+00
3	QR_3_1751917785	2025-07-07 19:49:45.182824+00	3	2025-07-07 20:00:52.421126+00
4	QR_6_1751917785	2025-07-07 19:49:45.910626+00	6	2025-07-07 20:00:53.550973+00
5	QR_7_1751917786	2025-07-07 19:49:46.065184+00	7	2025-07-07 20:00:54.651131+00
6	QR_11_1751917787	2025-07-07 19:49:47.285857+00	11	2025-07-07 20:00:55.830713+00
7	QR_12_1751917787	2025-07-07 19:49:47.454649+00	12	2025-07-07 20:00:56.940009+00
8	QR_8_1751918184	2025-07-07 19:56:24.365084+00	8	2025-07-07 20:00:58.057145+00
9	QR_10_1751918184	2025-07-07 19:56:24.459822+00	10	2025-07-07 20:00:59.194145+00
10	QR_9_1751918184	2025-07-07 19:56:24.561708+00	9	2025-07-07 20:01:00.315637+00
11	QR_SARAH_1_$(date +%s)	2025-07-07 20:17:41.476305+00	3	\N
12	QR_SARAH_2_$(date +%s)	2025-07-07 20:18:08.696436+00	3	\N
13	test-sterile-sample	2025-07-09 22:43:23.251993+00	3	2025-07-09 22:43:41.029089+00
14	QR-CODE-Test-4	2025-07-10 21:08:17.238996+00	3	2025-07-10 21:11:04.997278+00
\.


--
-- Data for Name: users_results; Type: TABLE DATA; Schema: public; Owner: bugsenseadmin
--

COPY public.users_results (id, infection_detected, species, concentration, antibiotic, created_at, qr_code_id, user_id, status) FROM stdin;
12	\N				2025-07-07 20:18:08.697637+00	12	3	ongoing
11	t				2025-07-07 20:17:41.477541+00	11	3	preliminary_assessment
10	t	Efaecalis	medium	Ciprofloxacin	2025-07-07 19:56:24.562738+00	10	9	closed
8	t	Ehormaechei	medium	Ciprofloxacin	2025-07-07 19:56:24.366336+00	8	8	ready
6	t	Paeruginosa	high	Penicillin	2025-07-07 19:49:47.287841+00	6	11	ready
2	t	Pmirabilis	low	Azithromycin	2025-07-07 19:49:45.003238+00	2	4	closed
1	t	Ecoli	high	Azithromycin	2025-07-07 19:49:44.810795+00	1	5	closed
3	f	Sterile			2025-07-07 19:49:45.183694+00	3	3	closed
4	f	Sterile			2025-07-07 19:49:45.912151+00	4	6	ready
5	f	Sterile			2025-07-07 19:49:46.066474+00	5	7	ready
7	f	Sterile			2025-07-07 19:49:47.455823+00	7	12	ready
9	f	Sterile			2025-07-07 19:56:24.460803+00	9	10	closed
13	f	Sterile			2025-07-09 22:43:23.25541+00	13	3	closed
14	t	Ecoli	Low		2025-07-10 21:08:17.242792+00	14	3	ready
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 29, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 51, true);


--
-- Name: institutions_institution_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.institutions_institution_id_seq', 2, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 8, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 84, true);


--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.users_customuser_groups_id_seq', 1, false);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.users_customuser_id_seq', 16, true);


--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.users_customuser_user_permissions_id_seq', 1, false);


--
-- Name: users_qrcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.users_qrcode_id_seq', 14, true);


--
-- Name: users_results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bugsenseadmin
--

SELECT pg_catalog.setval('public.users_results_id_seq', 14, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: institutions_doctor institutions_doctor_doctor_id_key; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.institutions_doctor
    ADD CONSTRAINT institutions_doctor_doctor_id_key UNIQUE (doctor_id);


--
-- Name: institutions_doctor institutions_doctor_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.institutions_doctor
    ADD CONSTRAINT institutions_doctor_pkey PRIMARY KEY (customuser_ptr_id);


--
-- Name: institutions_institution institutions_institution_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.institutions_institution
    ADD CONSTRAINT institutions_institution_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_email_key UNIQUE (email);


--
-- Name: users_customuser_groups users_customuser_groups_customuser_id_group_id_76b619e3_uniq; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_customuser_id_group_id_76b619e3_uniq UNIQUE (customuser_id, group_id);


--
-- Name: users_customuser_groups users_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_pkey PRIMARY KEY (id);


--
-- Name: users_customuser_user_permissions users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: users_customuser_user_permissions users_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_qrcode users_qrcode_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_qrcode
    ADD CONSTRAINT users_qrcode_pkey PRIMARY KEY (id);


--
-- Name: users_results users_results_pkey; Type: CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_results
    ADD CONSTRAINT users_results_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: institutions_doctor_doctor_id_f28bab4a_like; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX institutions_doctor_doctor_id_f28bab4a_like ON public.institutions_doctor USING btree (doctor_id varchar_pattern_ops);


--
-- Name: institutions_doctor_institution_id_7d551850; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX institutions_doctor_institution_id_7d551850 ON public.institutions_doctor USING btree (institution_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_customuser_assigned_doctor_id_e698596e; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_customuser_assigned_doctor_id_e698596e ON public.users_customuser USING btree (assigned_doctor_id);


--
-- Name: users_customuser_email_6445acef_like; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_customuser_email_6445acef_like ON public.users_customuser USING btree (email varchar_pattern_ops);


--
-- Name: users_customuser_groups_customuser_id_958147bf; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_customuser_groups_customuser_id_958147bf ON public.users_customuser_groups USING btree (customuser_id);


--
-- Name: users_customuser_groups_group_id_01390b14; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_customuser_groups_group_id_01390b14 ON public.users_customuser_groups USING btree (group_id);


--
-- Name: users_customuser_user_permissions_customuser_id_5771478b; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_customuser_user_permissions_customuser_id_5771478b ON public.users_customuser_user_permissions USING btree (customuser_id);


--
-- Name: users_customuser_user_permissions_permission_id_baaa2f74; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_customuser_user_permissions_permission_id_baaa2f74 ON public.users_customuser_user_permissions USING btree (permission_id);


--
-- Name: users_qrcode_user_id_d1b6a246; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_qrcode_user_id_d1b6a246 ON public.users_qrcode USING btree (user_id);


--
-- Name: users_results_qr_code_id_332262fe; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_results_qr_code_id_332262fe ON public.users_results USING btree (qr_code_id);


--
-- Name: users_results_user_id_3cbfb6ef; Type: INDEX; Schema: public; Owner: bugsenseadmin
--

CREATE INDEX users_results_user_id_3cbfb6ef ON public.users_results USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: institutions_doctor institutions_doctor_customuser_ptr_id_1dc4a498_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.institutions_doctor
    ADD CONSTRAINT institutions_doctor_customuser_ptr_id_1dc4a498_fk_users_cus FOREIGN KEY (customuser_ptr_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: institutions_doctor institutions_doctor_institution_id_7d551850_fk_instituti; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.institutions_doctor
    ADD CONSTRAINT institutions_doctor_institution_id_7d551850_fk_instituti FOREIGN KEY (institution_id) REFERENCES public.institutions_institution(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_users_cus FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser users_customuser_assigned_doctor_id_e698596e_fk_instituti; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_assigned_doctor_id_e698596e_fk_instituti FOREIGN KEY (assigned_doctor_id) REFERENCES public.institutions_doctor(customuser_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_gro_customuser_id_958147bf_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_gro_customuser_id_958147bf_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_groups_group_id_01390b14_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_group_id_01390b14_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_customuser_id_5771478b_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_customuser_id_5771478b_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_permission_id_baaa2f74_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_permission_id_baaa2f74_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_qrcode users_qrcode_user_id_d1b6a246_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_qrcode
    ADD CONSTRAINT users_qrcode_user_id_d1b6a246_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_results users_results_qr_code_id_332262fe_fk_users_qrcode_id; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_results
    ADD CONSTRAINT users_results_qr_code_id_332262fe_fk_users_qrcode_id FOREIGN KEY (qr_code_id) REFERENCES public.users_qrcode(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_results users_results_user_id_3cbfb6ef_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: bugsenseadmin
--

ALTER TABLE ONLY public.users_results
    ADD CONSTRAINT users_results_user_id_3cbfb6ef_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: bugsenseadmin
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

